name: Stable
on: [push, pull_request]
permissions:
  contents: write
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [4.1.1]
        abi: [cp39]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker build docker/manylinux -t med/manylinux
          docker run --rm -e MAKEFLAGS='-j2' -v `pwd`:/io med/manylinux /io/build-wheels-linux.sh ${{ matrix.version }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wheelhouse/salome_med-${{ matrix.version }}-${{ matrix.abi }}-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash -l {0}
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          conda install -y twine
          twine upload --non-interactive wheelhouse/*.whl

  windows:
    runs-on: windows-latest
    permissions:
      contents: write 
    strategy:
      matrix:
        include:
          - abi: cp39
            python-version: '3.9'
            version: 4.1.1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: true
      - name: Build
        shell: cmd
        run: call .\build-wheels-windows.bat ${{ matrix.version }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wheelhouse/salome_med-${{ matrix.version }}-${{ matrix.abi }}-abi3-win_amd64.whl
      - name: Upload
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash -l {0}
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          conda install -y twine
          twine upload --non-interactive wheelhouse/*.whl

